Vagrant.configure("2") do |config|
  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.box_check_update = false
    db.vm.network "forwarded_port", guest: 3306, host: 3307
    db.vm.network "private_network", ip: "192.168.33.10"
    db.vm.synced_folder "./db", "/vagrant_data"

    # VirtualBox provider settings
    db.vm.provider "virtualbox" do |vb|
      vb.gui = false            # Disable GUI
      vb.memory = "1024"        # Set memory (in MB)
      vb.name = "db"           # Set VM name
    end
  end
end
