Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "bento/ubuntu-22.04"
    web.vm.box_check_update = false
    web.vm.network "forwarded_port", guest: 8086, host: 8086
    web.vm.network "private_network", ip: "192.168.33.11"
    web.vm.synced_folder "./web", "/vagrant_data"

    # VirtualBox provider settings
    web.vm.provider "virtualbox" do |vb|
      vb.gui = false            # Disable GUI
      vb.memory = "1024"        # Set memory (in MB)
      vb.name = "web"           # Set VM name
    end
  end
end
